// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zwaxmctmgvavyacmauts.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp3YXhtY3RtZ3ZhdnlhY21hdXRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3NTcwNDUsImV4cCI6MjA2MzMzMzA0NX0.WHE-bFbFrBnjIe3RK-b4munyA0RGOeNh9X3VWbSGCdM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);